### ISSUE TITLE
Convert Jira issues to Github issues and import

### ISSUE THREAD

**Issue by ddeimeke** [GothenburgBitFactory/infrastructure#3]

**Comment by pbeckingham** [comment]
Complete conversion test run finished late 2018-02-07. Tomáš will run the real thing starting probably Sunday.

**Comment by wbsch** [comment]
Attachments seem to be missing in (at least) https://github.com/tbabej/testimportfinal/issues/270 (TW-296). Is that fixed? I mentioned it on Slack, not sure anyone saw.

**Comment by tbabej** [comment]
Attachments are going to be added manually, migration tool just downloads
them and labels them appropriately. Paul is going to manually upload them
since that functionality is not exposed in the API, and using something
like Selenium for this seems like a overkill.

**Comment by wbsch** [comment]
How many attachments are there? If it'd pay off to automate that I can look into it, I have some experience with Selenium / web automation, it shouldn't take too long. GitHub deciding to throttle or throw up captchas could be a bit of a problem, of course.

**Comment by tbabej** [comment]
There are 406 attachments across 280 issues.

**Comment by recollir** [comment]
jira is RIP. Thanks for the migration, @tbabej .
