### ISSUE TITLE
Migrate tasktools.org content

### ISSUE THREAD

**Issue by pbeckingham** [GothenburgBitFactory/infrastructure#9]
- [ ] Migrate all the tasktools.org content to gothenburgbitfactory.org

- [x] Rename the tt.org.git repository to gbf.org.git

- [x] Add git hooks to automate pushes to gbf.org.git to update the website.

**Comment by recollir** [comment]
- tt.org migrateted to gbf.org on GitHub. Still pushed to tasktools.org.

**Comment by recollir** [comment]
Moved to GothenburgBitFactory/gbf.org#1
